name: Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Semgrep
      working-directory: AwesomePasswordChecker
      run: pip install semgrep

    - name: Run Checkstyle
      working-directory: AwesomePasswordChecker
      run: mvn checkstyle:check

    - name: Run Unit Tests
      working-directory: AwesomePasswordChecker
      run: mvn test

    - name: Run Coverage Analysis
      working-directory: AwesomePasswordChecker
      run: mvn jacoco:report

    - name: Ensure 90% Coverage
      run: |
        COVERAGE=$(mvn jacoco:report | grep -oP 'TOTAL\s+\K\d+')
        if [ "$COVERAGE" -lt 90 ]; then
          echo "Coverage is below 90%: $COVERAGE"
          exit 1
        fi

    - name: Run Performance Tests
      working-directory: AwesomePasswordChecker
      run: mvn test -Pperformance
