name: Deploy Javadoc

on:
  push:
    branches:
      - main

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set Up Java Environment
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Generate Javadoc (In Project Directory)
    - name: Generate Javadoc
      run: mvn clean javadoc:javadoc
      working-directory: AwesomePasswordChecker

    # Step 4: Deploy Javadoc to GH-Pages
    - name: Deploy to GH-Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: AwesomePasswordChecker/target/site/apidocs
        branch: gh-pages
        destination_dir: javadoc/3.4.1

    # Step 5: Add CNAME (Optional for Custom Domains)
    - name: Add CNAME
      run: echo 'blah.com' > AwesomePasswordChecker/target/site/apidocs/CNAME
